version: '3'
services:
  myapp:
    build: .
    command: python app.py
    volumes:
      - ./ptt:/usr/src/app
  mqtt:
    build: .
    command: python app.py
    volumes:
      - ./mqtt:/usr/src/app
      - ./cert:/usr/src/cert
  redis:
    build: .
    command: python app.py
    volumes:
      - ./myRedis:/usr/src/app
      - ./cert:/usr/src/cert
  vault:
    build: .
    command: python app.py
    environment:
      VAULT_ADDR: https://<my_vault_url>
      VAULT_ROLE: admin
    volumes:
      - ./vault:/usr/src/app
      - ~/.aws:/root/.aws
#  web:
#    build: .
#    command: gunicorn -b 0.0.0.0:8000 todosapp.wsgi:application
#    depends_on:
#      - postgres
#    volumes:
#      - .:/usr/src/app
#    ports:
#      - "8000:8000"
#    environment:
#      DATABASE_URL: postgres://todoapp@postgres/todos
